apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  labels:
    app: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello-app
        image: docker7gm/hello-app:v0.0.3
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: regcredentials