apiVersion: v1
kind: Service
metadata:
  name: hello-service-lb
  labels:
    app: hello
spec:
  selector:
    app: hello
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer