apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
  labels:
    app: ubuntu-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ubuntu-server
  template:
    metadata:
      labels:
        app: ubuntu-server
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: pvc1
      containers:
      - name: ubuntu
        image: ubuntu:latest
        command: ["/bin/sleep", "30m"]